# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: config
description: View and edit Google Cloud CLI properties.
commands:
    - name: list
      description: List Google Cloud CLI properties for the currently active configuration.
      flags:
        --all: List all set and unset properties that match the arguments.
        --filter=: Apply a Boolean filter _EXPRESSION_ to each resource item to be listed.
        --limit=: Maximum number of resources to list.
        --no-all&: List all set and unset properties that match the arguments.
        --sort-by=: Comma-separated list of resource field key names to sort by.
    - name: set
      description: Set a Google Cloud CLI property.
      flags:
        --installation: If set, the property is updated for the entire Google Cloud CLI
        --no-installation&: If set, the property is updated for the entire Google Cloud CLI
    - name: universe-descriptors
      description: Manage the universe descriptor data.
      hidden: true
      commands:
        - name: create
          description: Create a new universe descriptor data entry.
          hidden: true
        - name: delete
          description: Delete universe descriptor data.
          hidden: true
        - name: describe
          description: Describe universe descriptor data dict in the cache.
          hidden: true
        - name: list
          description: List cached universe descriptors.
          hidden: true
          flags:
            --filter=: Apply a Boolean filter _EXPRESSION_ to each resource item to be listed.
            --limit=: Maximum number of resources to list.
            --sort-by=: Comma-separated list of resource field key names to sort by.
        - name: update
          description: Update universe descriptor data in the cache.
          hidden: true
    - name: unset
      description: Unset a Google Cloud CLI property.
      flags:
        --installation: If set, the property is updated for the entire Google Cloud CLI
        --no-installation&: If set, the property is updated for the entire Google Cloud CLI
    - name: virtualenv
      description: Manage Cloud SDK virtual env setup.
      hidden: true
      commands:
        - name: create
          description: Create a virtualenv environment.
          hidden: true
          flags:
            --python-to-use=: Absolute path to python to use to create virtual env.
        - name: delete
          description: Delete a virtualenv environment.
          hidden: true
        - name: describe
          description: Describe a virtualenv environment.
          hidden: true
        - name: disable
          description: Disable a virtualenv environment.
          hidden: true
        - name: enable
          description: Enable a virtualenv environment.
          hidden: true
        - name: update
          description: Update modules installed in a virtualenv environment.
          hidden: true
    - name: config-helper
      description: A helper for providing auth and config data to external tools.
      hidden: true
      flags:
        --force-auth-refresh: Force a refresh of the credentials even if they have not yet expired.
        --min-expiry=: If given, refresh the credentials if they are within MIN_EXPIRY from expiration.
        --no-force-auth-refresh&: Force a refresh of the credentials even if they have not yet expired.
    - name: configurations
      description: Manage the set of gcloud named configurations.
      commands:
        - name: activate
          description: Activates an existing named configuration.
        - name: create
          description: Creates a new named configuration.
          flags:
            --activate: If true, activate this configuration upon create.
            --no-activate&: If true, activate this configuration upon create.
        - name: delete
          description: Deletes a named configuration.
        - name: describe
          description: Describes a named configuration by listing its properties.
          flags:
            --all: Include unset properties in output.
            --no-all&: Include unset properties in output.
        - name: list
          description: Lists existing named configurations.
          flags:
            --filter=: Apply a Boolean filter _EXPRESSION_ to each resource item to be listed.
            --limit=: Maximum number of resources to list.
            --sort-by=: Comma-separated list of resource field key names to sort by.
        - name: rename
          description: Renames a named configuration.
          flags:
            --new-name=!: Specifies the new name of the configuration.
    - name: get
      description: Print the value of a Google Cloud CLI property.
    - name: get-value
      description: Alias for `gcloud config get`, for backwards compatibility.
      hidden: true
