# yaml-language-server: $schema=https://carapace.sh/schemas/command.json
name: telco-automation
description: Manage Telco Automation resources.
commands:
    - name: operations
      description: Command group for working with telco automation operations.
      commands:
        - name: describe
          description: Get description of a long-running telco automation operation.
          flags:
            --location=: The location name.
        - name: wait
          description: Poll long-running telco automation operation until it completes.
          flags:
            --location=: The location name.
    - name: orchestration-cluster
      description: Manage telco automation orchestration cluster instances.
      commands:
        - name: create
          description: Create a telco automation orchestration cluster.
          flags:
            --async: Return immediately, without waiting for the operation in progress to
            --cidr-blocks=: Master Authorized Network that supports multiple CIDR blocks.
            --cluster-cidr-block=: IP address range for the cluster pod IPs.
            --cluster-named-range=: Name of the existing secondary range in the cluster's subnetwork to use for pod IP addresses.
            --full-management-config: This parameter is to marked true only if the management configuration arguments which are provided, belong to full (Autopilot) cluster management.
            --location=: The location name.
            --master-ipv4-cidr-block=: /28 network that the control plane will use.
            --network=!: Name of the VPC Network to put the GKE cluster and nodes in.
            --no-async&: Return immediately, without waiting for the operation in progress to
            --no-full-management-config&: This parameter is to marked true only if the management configuration arguments which are provided, belong to full (Autopilot) cluster management.
            --services-cidr-block=: IP address range for the cluster service IPs.
            --services-named-range=: Name of the existing secondary range in the cluster's subnetwork to use for service ClusterIPs.
            --subnet=: Specifies the subnet that the interface will be part of.
        - name: delete
          description: Delete a telco automation orchestration cluster.
          flags:
            --async: Return immediately, without waiting for the operation in progress to
            --location=: The location name.
            --no-async&: Return immediately, without waiting for the operation in progress to
        - name: describe
          description: Show details about the orchestration cluster.
          flags:
            --location=: The location name.
        - name: list
          description: List telco automation orchestration clusters.
          flags:
            --filter=: Apply a Boolean filter _EXPRESSION_ to each resource item to be listed.
            --limit=: Maximum number of resources to list.
            --location=!: ID of the location or fully qualified identifier for the location.
            --no-uri&: Print a list of resource URIs instead of the default output, and change the
            --page-size=: Some services group resource list output into pages.
            --sort-by=: Comma-separated list of resource field key names to sort by.
            --uri: Print a list of resource URIs instead of the default output, and change the
